### ISSUE TITLE
Typo in configure.php

### ISSUE THREAD

**Issue by BigManatee** [spatie/package-skeleton-php#74]
Firstly, apologies for being too lazy to submit a PR for super minor issues!

Indenting is off on [L166 ](https://github.com/spatie/package-skeleton-php/blob/main/configure.php#L166) and typo on [L167](https://github.com/spatie/package-skeleton-php/blob/main/configure.php#L167) within the comment (`nothign`).

**Comment by freekmurze** [comment]
Fixed, feel free to send a PR for other things that are off.
